version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn
      # テスト
      - run: yarn test
      # ビルド
      - run: yarn build
      # cliからNetlifyにデプロイできるようにするライブラリをインストール
      - run: yarn add netlify-cli
      # デプロイコマンド
      - run: yarn netlify deploy -p -d build -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_POKEDEX2_ID}

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
