version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
executors:
  node:
    docker:
      - image: circleci/node:14
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_modules:
    steps:
      - save_cache:
          key:  dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  set_up:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: Install npm dependencies
          command: yarn
      - save_modules
  eslint:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: Run eslint
          command: yarn eslint
      - save_modules
  type_check:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: Run type check
          command: yarn type-check
      - save_modules
  jest_run:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: Run unit test
          command: yarn test
      - save_modules
  build and deploy:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: build
          command: yarn build:prod
      - run:
          name: deploy
          command: yarn netlify deploy -p -d build -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_POKEDEX2_ID}

workflows:
  test:
    jobs:
      - set_up:
          filters:
            branches:
              only: /.*/
      - eslint:
          filters:
            branches:
              only: /.*/
          requires:
            - set_up
      - type_check:
          filters:
            branches:
              only: /.*/
          requires:
            - set_up
      - jest_run:
          filters:
            branches:
              only: /.*/
          requires:
            - set_up
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          filters:
            branches:
              only: /.*/
          requires:
            - set_up
  build-and-deploy:
    jobs:
      - build and deploy:
          filters:
            branches:
              only: master
