version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
executors:
  node:
    docker:
      - image: circleci/node:14
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_modules:
    steps:
      - save_cache:
          key:  dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  jest_run:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run: yarn
      - run: yarn test
      - save_modules
  build and deploy:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run: yarn
      - run: yarn build
      - run: yarn netlify deploy -p -d build -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_POKEDEX2_ID}

workflows:
  build-test-deploy:
    jobs:
      - jest_run:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build and deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
